# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/center.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/center.proto',
  package='center',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13protos/center.proto\x12\x06\x63\x65nter\"0\n\x0fRegisterRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0c\n\x04keys\x18\x02 \x03(\x05\"\x1d\n\x0eMappingRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\"\x0e\n\x0c\x45mptyRequest\"\x1a\n\x08IntReply\x12\x0e\n\x06retval\x18\x01 \x01(\x05\"\x1d\n\x0bStringReply\x12\x0e\n\x06retval\x18\x01 \x01(\t2\xb2\x01\n\x0c\x43\x65nterServer\x12\x37\n\x08register\x12\x17.center.RegisterRequest\x1a\x10.center.IntReply\"\x00\x12\x38\n\x07mapping\x12\x16.center.MappingRequest\x1a\x13.center.StringReply\"\x00\x12/\n\x03\x65nd\x12\x14.center.EmptyRequest\x1a\x10.center.IntReply\"\x00\x62\x06proto3'
)




_REGISTERREQUEST = _descriptor.Descriptor(
  name='RegisterRequest',
  full_name='center.RegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service', full_name='center.RegisterRequest.service', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keys', full_name='center.RegisterRequest.keys', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=79,
)


_MAPPINGREQUEST = _descriptor.Descriptor(
  name='MappingRequest',
  full_name='center.MappingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='center.MappingRequest.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=110,
)


_EMPTYREQUEST = _descriptor.Descriptor(
  name='EmptyRequest',
  full_name='center.EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=126,
)


_INTREPLY = _descriptor.Descriptor(
  name='IntReply',
  full_name='center.IntReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='retval', full_name='center.IntReply.retval', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=154,
)


_STRINGREPLY = _descriptor.Descriptor(
  name='StringReply',
  full_name='center.StringReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='retval', full_name='center.StringReply.retval', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=185,
)

DESCRIPTOR.message_types_by_name['RegisterRequest'] = _REGISTERREQUEST
DESCRIPTOR.message_types_by_name['MappingRequest'] = _MAPPINGREQUEST
DESCRIPTOR.message_types_by_name['EmptyRequest'] = _EMPTYREQUEST
DESCRIPTOR.message_types_by_name['IntReply'] = _INTREPLY
DESCRIPTOR.message_types_by_name['StringReply'] = _STRINGREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'protos.center_pb2'
  # @@protoc_insertion_point(class_scope:center.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

MappingRequest = _reflection.GeneratedProtocolMessageType('MappingRequest', (_message.Message,), {
  'DESCRIPTOR' : _MAPPINGREQUEST,
  '__module__' : 'protos.center_pb2'
  # @@protoc_insertion_point(class_scope:center.MappingRequest)
  })
_sym_db.RegisterMessage(MappingRequest)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYREQUEST,
  '__module__' : 'protos.center_pb2'
  # @@protoc_insertion_point(class_scope:center.EmptyRequest)
  })
_sym_db.RegisterMessage(EmptyRequest)

IntReply = _reflection.GeneratedProtocolMessageType('IntReply', (_message.Message,), {
  'DESCRIPTOR' : _INTREPLY,
  '__module__' : 'protos.center_pb2'
  # @@protoc_insertion_point(class_scope:center.IntReply)
  })
_sym_db.RegisterMessage(IntReply)

StringReply = _reflection.GeneratedProtocolMessageType('StringReply', (_message.Message,), {
  'DESCRIPTOR' : _STRINGREPLY,
  '__module__' : 'protos.center_pb2'
  # @@protoc_insertion_point(class_scope:center.StringReply)
  })
_sym_db.RegisterMessage(StringReply)



_CENTERSERVER = _descriptor.ServiceDescriptor(
  name='CenterServer',
  full_name='center.CenterServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=188,
  serialized_end=366,
  methods=[
  _descriptor.MethodDescriptor(
    name='register',
    full_name='center.CenterServer.register',
    index=0,
    containing_service=None,
    input_type=_REGISTERREQUEST,
    output_type=_INTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='mapping',
    full_name='center.CenterServer.mapping',
    index=1,
    containing_service=None,
    input_type=_MAPPINGREQUEST,
    output_type=_STRINGREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='end',
    full_name='center.CenterServer.end',
    index=2,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_INTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CENTERSERVER)

DESCRIPTOR.services_by_name['CenterServer'] = _CENTERSERVER

# @@protoc_insertion_point(module_scope)
