# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import center_pb2 as protos_dot_center__pb2


class CenterServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register = channel.unary_unary(
                '/center.CenterServer/register',
                request_serializer=protos_dot_center__pb2.RegisterRequest.SerializeToString,
                response_deserializer=protos_dot_center__pb2.IntReply.FromString,
                )
        self.mapping = channel.unary_unary(
                '/center.CenterServer/mapping',
                request_serializer=protos_dot_center__pb2.MappingRequest.SerializeToString,
                response_deserializer=protos_dot_center__pb2.StringReply.FromString,
                )
        self.end = channel.unary_unary(
                '/center.CenterServer/end',
                request_serializer=protos_dot_center__pb2.EmptyRequest.SerializeToString,
                response_deserializer=protos_dot_center__pb2.IntReply.FromString,
                )


class CenterServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def mapping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def end(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CenterServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=protos_dot_center__pb2.RegisterRequest.FromString,
                    response_serializer=protos_dot_center__pb2.IntReply.SerializeToString,
            ),
            'mapping': grpc.unary_unary_rpc_method_handler(
                    servicer.mapping,
                    request_deserializer=protos_dot_center__pb2.MappingRequest.FromString,
                    response_serializer=protos_dot_center__pb2.StringReply.SerializeToString,
            ),
            'end': grpc.unary_unary_rpc_method_handler(
                    servicer.end,
                    request_deserializer=protos_dot_center__pb2.EmptyRequest.FromString,
                    response_serializer=protos_dot_center__pb2.IntReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'center.CenterServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CenterServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/center.CenterServer/register',
            protos_dot_center__pb2.RegisterRequest.SerializeToString,
            protos_dot_center__pb2.IntReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def mapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/center.CenterServer/mapping',
            protos_dot_center__pb2.MappingRequest.SerializeToString,
            protos_dot_center__pb2.StringReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def end(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/center.CenterServer/end',
            protos_dot_center__pb2.EmptyRequest.SerializeToString,
            protos_dot_center__pb2.IntReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
