# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/peer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/peer.proto',
  package='peer',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11protos/peer.proto\x12\x04peer\"+\n\rInsertRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\"\x1b\n\x0cQueryRequest\x12\x0b\n\x03key\x18\x01 \x01(\x05\"\x0e\n\x0c\x45mptyRequest\" \n\rActiveRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\x1a\n\x08IntReply\x12\x0e\n\x06retval\x18\x01 \x01(\x05\"\x1d\n\x0bStringReply\x12\x0e\n\x06retval\x18\x01 \x01(\t2\xcd\x01\n\nPeerServer\x12/\n\x06insert\x12\x13.peer.InsertRequest\x1a\x0e.peer.IntReply\"\x00\x12\x30\n\x05query\x12\x12.peer.QueryRequest\x1a\x11.peer.StringReply\"\x00\x12/\n\x06\x61\x63tive\x12\x13.peer.ActiveRequest\x1a\x0e.peer.IntReply\"\x00\x12+\n\x03\x65nd\x12\x12.peer.EmptyRequest\x1a\x0e.peer.IntReply\"\x00\x62\x06proto3'
)




_INSERTREQUEST = _descriptor.Descriptor(
  name='InsertRequest',
  full_name='peer.InsertRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='peer.InsertRequest.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='peer.InsertRequest.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=70,
)


_QUERYREQUEST = _descriptor.Descriptor(
  name='QueryRequest',
  full_name='peer.QueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='peer.QueryRequest.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=99,
)


_EMPTYREQUEST = _descriptor.Descriptor(
  name='EmptyRequest',
  full_name='peer.EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=115,
)


_ACTIVEREQUEST = _descriptor.Descriptor(
  name='ActiveRequest',
  full_name='peer.ActiveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service', full_name='peer.ActiveRequest.service', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=149,
)


_INTREPLY = _descriptor.Descriptor(
  name='IntReply',
  full_name='peer.IntReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='retval', full_name='peer.IntReply.retval', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=177,
)


_STRINGREPLY = _descriptor.Descriptor(
  name='StringReply',
  full_name='peer.StringReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='retval', full_name='peer.StringReply.retval', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=208,
)

DESCRIPTOR.message_types_by_name['InsertRequest'] = _INSERTREQUEST
DESCRIPTOR.message_types_by_name['QueryRequest'] = _QUERYREQUEST
DESCRIPTOR.message_types_by_name['EmptyRequest'] = _EMPTYREQUEST
DESCRIPTOR.message_types_by_name['ActiveRequest'] = _ACTIVEREQUEST
DESCRIPTOR.message_types_by_name['IntReply'] = _INTREPLY
DESCRIPTOR.message_types_by_name['StringReply'] = _STRINGREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InsertRequest = _reflection.GeneratedProtocolMessageType('InsertRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTREQUEST,
  '__module__' : 'protos.peer_pb2'
  # @@protoc_insertion_point(class_scope:peer.InsertRequest)
  })
_sym_db.RegisterMessage(InsertRequest)

QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYREQUEST,
  '__module__' : 'protos.peer_pb2'
  # @@protoc_insertion_point(class_scope:peer.QueryRequest)
  })
_sym_db.RegisterMessage(QueryRequest)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYREQUEST,
  '__module__' : 'protos.peer_pb2'
  # @@protoc_insertion_point(class_scope:peer.EmptyRequest)
  })
_sym_db.RegisterMessage(EmptyRequest)

ActiveRequest = _reflection.GeneratedProtocolMessageType('ActiveRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVEREQUEST,
  '__module__' : 'protos.peer_pb2'
  # @@protoc_insertion_point(class_scope:peer.ActiveRequest)
  })
_sym_db.RegisterMessage(ActiveRequest)

IntReply = _reflection.GeneratedProtocolMessageType('IntReply', (_message.Message,), {
  'DESCRIPTOR' : _INTREPLY,
  '__module__' : 'protos.peer_pb2'
  # @@protoc_insertion_point(class_scope:peer.IntReply)
  })
_sym_db.RegisterMessage(IntReply)

StringReply = _reflection.GeneratedProtocolMessageType('StringReply', (_message.Message,), {
  'DESCRIPTOR' : _STRINGREPLY,
  '__module__' : 'protos.peer_pb2'
  # @@protoc_insertion_point(class_scope:peer.StringReply)
  })
_sym_db.RegisterMessage(StringReply)



_PEERSERVER = _descriptor.ServiceDescriptor(
  name='PeerServer',
  full_name='peer.PeerServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=211,
  serialized_end=416,
  methods=[
  _descriptor.MethodDescriptor(
    name='insert',
    full_name='peer.PeerServer.insert',
    index=0,
    containing_service=None,
    input_type=_INSERTREQUEST,
    output_type=_INTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='query',
    full_name='peer.PeerServer.query',
    index=1,
    containing_service=None,
    input_type=_QUERYREQUEST,
    output_type=_STRINGREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='active',
    full_name='peer.PeerServer.active',
    index=2,
    containing_service=None,
    input_type=_ACTIVEREQUEST,
    output_type=_INTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='end',
    full_name='peer.PeerServer.end',
    index=3,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_INTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PEERSERVER)

DESCRIPTOR.services_by_name['PeerServer'] = _PEERSERVER

# @@protoc_insertion_point(module_scope)
